language: python
python:
  - '3.6'

before_install:
  - sudo apt-get -y install libcurl4-gnutls-dev libgnutls-dev
  - pip install -U pip setuptools

install: 
  - python setup.py install

script: 
  # Code style check
  - flake8 src
  
  # Verification-1 - Was installation successfule? 
  - tng-bench --help
  
  # Unit test would go here
  - pytest --show-capture all -s -v src/tngsdk/benchmark/tests/test_osm_pdriver
  # - pytest -v