language: python
python:
  - '3.6'

before_install:
  - sudo apt-get -y install libcurl4-gnutls-dev libgnutls-dev
  - pip install -U pip setuptools

install: 
  - python setup.py install

script: 
  - flake8 src
  # Unit test would go here
  # -python setup.py test