global:
  scrape_interval:     2s # By default, scrape targets every 15 seconds.

scrape_configs:
  # static test - works
  - job_name: 'backflip1-node'
    static_configs:
      - targets: ['fgcn-backflip1.cs.uni-paderborn.de:9100']

  # Dynamic test - works
  - job_name: 'openstack-nova'
    openstack_sd_configs:
    - identity_endpoint: http://fgcn-backflip9.cs.uni-paderborn.de/identity
      project_name: admin
      username: admin
      password: admin
      role: instance
      region: RegionOne

    relabel_configs:
      # Keep only active instances
      - source_labels: [__meta_openstack_instance_status]
        action: keep
        regex: ACTIVE